### ISSUE TITLE
[1.10.2] Tails not showing up.

### ISSUE THREAD

**Issue by MidnightvonCorgstein** [kihira/Tails#102]
Hello, I have a modpack, and the tails do not show up, along with more player models changes, and no model changes seem to show at all, besides mpm HD skins, I never had any problems with mpm and tails until they stopped rendering altogether. It doesn't show on client nor server, and the log doesn't show any errors even on debug mode or with sasit turned off, I also never had errors with optifine, even with optifine disabled, and with liteloader disabled. heres my big old mod list (warning, its huge): http://modlister.com/user/SummerChanFoxx

**Comment by kihira** [comment]
Sorry for the delay on this.

Hmm, it should work with MPM but I can't remember if it's broken in that version.
If you're still playing this modpack, are you still having this issue?
