### ISSUE TITLE
issues with the appearance of the model (on the Ears only)

### ISSUE THREAD

**Issue by HBRINE** [kihira/Tails#106]
I said ears only, because I only use ears and a tail, **the ears keep staying still not moving with my skin/player model/player skin's model's head!** sorry if that's confusing, I meant my skin/model of my Minecraft user/player, has it's head moving when I want it to, but the ears float above me head when looking upwards, or downwards, either way, it will do that, the ears model is the top ear type you can choose, that's just below "None", and I don't like it, here's 3 screenshots of it.

Below are the photos

![2018-07-20_22 58 27](https://user-images.githubusercontent.com/31017915/43031575-54b8a262-8c72-11e8-9dd1-1969e55d1618.png)
![2018-07-20_22 58 31](https://user-images.githubusercontent.com/31017915/43031579-57c3318e-8c72-11e8-882f-64a3379b84e5.png)
![2018-07-20_22 58 40](https://user-images.githubusercontent.com/31017915/43031580-5a991522-8c72-11e8-9f6d-6c5b9417e3fc.png)

**Comment by HBRINE** [comment]
I'm using forge to get the SignPicture 1.12.2 mod, i'm using 1.12.2 as my version of Minecraft in these screenshots, that's how I have Souron's Eye as a GIF in my inventory from holding Left Ctrl, and press Middle Click on the sign with the GIF or any other image, but you can't use video format files.

**Comment by HBRINE** [comment]
that's the explanation to my Eye of Souron sign picture item.

**Comment by HBRINE** [comment]
also if you aren't reading it, I mentioned I'm using 1.12.2 as my version of Minecraft.

and read below


### 1.13 IS NOW OUT FROM THE 1-3 DAYS BEFORE THIS ISSUE WAS CREATED BY ME ###

**YYYYYYYYYYYAAAAAAAAAAAAAAAAAAYYYYYYYYYYYYYYYYYY**

(1.13 really is out on that time, for the US Minecraft, it's Java Edition's LATEST version.)

**Comment by kihira** [comment]
This usually occurs if you're using another mod that modifies the player model in some way. Do you have something like Mo'bends or anything that causes your player to do different things?

**Comment by HBRINE** [comment]
![mods_picture_for_tails_mod_1 12 2_issue_i_made](https://user-images.githubusercontent.com/31017915/43110242-dadcd03c-8eb8-11e8-9d29-18ce56a20fc0.PNG)
I hope this helps to find out which one(s) are doing this problem.

**Comment by HBRINE** [comment]
these are all my mods I have currently, tell me which of them does mess with my player model

**Comment by HBRINE** [comment]
![get_well_soon](https://user-images.githubusercontent.com/31017915/43110403-bf4b0270-8eb9-11e8-93ff-6c144e9e2788.gif)
^^^^^^^^^^^^^^^^^^^
I mean "Get Well Soon" as, "Get Well Soon player model of mine."

**Comment by HBRINE** [comment]
I hope my `Minecraft` `Player Model` doesn't stay like this

**Comment by HBRINE** [comment]
> I hope this problem doesn't last forever.

**Comment by HBRINE** [comment]
> Edit for the comment about the picture of my mods: I accidentally left my cursor on there and click on it and took the cursor off and left the `CreativeCore-1.12.2` `.jar` file and it made it blue, sorry because I am thinking you will get confused about that you would think I knew which of the mods is messing with the player model, but I actually don't know, ok.

**Comment by HBRINE** [comment]
#94 Issue, is also having a problem, have you fixed it yet, it's causing the Import from String to not work for me too, I hope you fix it soon, I'm saying "HURRY UP!", I just need it fixed soon, but don't rush yourself, I'll roast (it's a joke hurts people's feelings and stuff) the people who try to rush you by putting comments for you to hurry up and fix the Import from String problem.

**Comment by HBRINE** [comment]
**I'll get rid of scrubs who annoy you by telling you to hurry up with the Import from String not working Issue**

**Comment by kihira** [comment]
It's possible the cosmetic wings mod might be interfering with the model, you could try removing it for now to see if the issue fixes itself. Optifine might also be causing it.

**Comment by HBRINE** [comment]
It was happening **before** the Cosmetics Wings was being used by me also other than the players who use it in their minecraft mod files.

**Comment by HBRINE** [comment]
I also **need** Optifine.

**Comment by kihira** [comment]
Another player has reported that "obfuscate" alters the player model which was causing issues, if you disable that it should then work correctly

**Comment by HBRINE** [comment]
I got rid of cgm, furniture mod, and obfuscate, all from MrCrayfish’s mods you can download, **and now it works again**

**Comment by kihira** [comment]
It's mostly obfuscate that's causing the issue. You can trying going into the Tails config file and enabling the legacy renderer too, that might also fix it but I'm going to close this issue for now
