### ISSUE TITLE
Fox ears seem quite far back. 

### ISSUE THREAD

**Issue by fsendventd** [kihira/Tails#115]
Should be fairly self-explanatory. 
![2019-04-02_07 02 19](https://user-images.githubusercontent.com/44233145/55409340-b7096b00-5516-11e9-9c57-16fe766c1797.png)

**Comment by kihira** [comment]
Intentional, it's more of a personal preference. Unfortunately without cluttering up the entire UI with duplicate parts in different positions, not easy to solve in the current version. However Tails 2 will allow you to place them wherever you like
