### ISSUE TITLE
Questions about future version(s)

### ISSUE THREAD

**Issue by GreenGhost21** [kihira/Tails#119]
Hello, I have a pair of questions regarding the future of this mod:

1. Will there be any more updates to the 1.12.2 version of this mod? Many, many mods are still only on 1.12.2, and it would be a shame to not be able to use new versions of this alongside them.
2. Would it be possible to add a framework to allow people to add their own assets to the mod before moving on from 1.12.2? 

Please give my requests some thought. I imagine there'd definitely be a demand for custom tails and such in a 1.12.2 version.

**Comment by kihira** [comment]
Yup, the current plan is to release Tails 2 for 1.12, just taking some time to get everything done!

**Comment by GreenGhost21** [comment]
Thanks for the response, I'm relieved and excited that the 1.12.2 version will continue to be developed!
