### ISSUE TITLE
Server Not Starting With Tails and FoxLib

### ISSUE THREAD

**Issue by Fireshot415** [kihira/Tails#47]
I have already solved the issue on IRC which got a very quick response and a working server so jump over there if you have the same issue!

If you find your server isn't starting then check the logs and look for the line 
"[main/INFO]: Requesting users input for FoxLib. Check your windows!"

If you see said line then redownload the latest version of each of Kihira's mods that you are using and the latest FoxLib! Ensure that each file remains exactly as it is when it is downloaded (which means DO NOT CHANGE THE NAME!) as Chrome and other browsers are likely to put a character at the end to signify that another file has already been downloaded with the same name. Ensure this doesn't happen!

If you have already followed through this and still have an error, then get onto [IRC](http://webchat.esper.net/?nick=&channels=kihira "IRC Link") and get support!

**Comment by kihira** [comment]
This should now be improved a lot with 1.3.1 and have better file name detection
