### ISSUE TITLE
Weird looking with Mo'Bends

### ISSUE THREAD

**Issue by sheosi** [kihira/Tails#51]
I'va tried tails with Mo'Bends and while it works it seems to have one problem, the tail's position is at the shoes not at the back, so either explicit compatibility or configurable position would be nice.

**Comment by kihira** [comment]
Unlikely this will ever be fixed, I've done all I can to add compatibility to body changing mods. 
If a mod changes the players model significantly, there is basically nothing I can do.

**Comment by Foxite** [comment]
I'd be interested in making a compatibility mod for these two. Although I'm not too experienced in cross-mod interaction, I did write a mod before, so it might just work.

Do you mind to explain me how I would change the tail positions? You don't have to spoonfeed code (in fact, I'd find it better if I had to figure it out myself), but an explanation of some methods I'd use would be nice.

**Comment by kihira** [comment]
Easiest way is to look at https://github.com/kihira/Tails/blob/develop/src/main/java/uk/kihira/tails/client/render/LayerPart.java
You can see how I fetch the part and render it, then just follow the methods called
