### ISSUE TITLE
Shark fins? Shark fins.

### ISSUE THREAD

**Issue by JAWSAWN** [kihira/Tails#52]
Aquatic furries needs some respect too! ;3

**Comment by Xiretza** [comment]
Exactly, show some love for those scalies x3

**Comment by kihira** [comment]
I actually have been given a shark tail https://twitter.com/KitsuneKihira/status/569484281501913089

I'm waiting to make the next build final as I'm currently working on something else. 
This will be coming eventually though

**Comment by kihira** [comment]
This was adding in the 1.4.0 release
