### ISSUE TITLE
Crashes upon clicking Tails Editor.

### ISSUE THREAD

**Issue by SYMA24G** [kihira/Tails#53]
The game crashes every time the tails editor button is clicked.
Here is the crash report.
https://www.dropbox.com/s/ph6yea4rb36mqt0/crash-2015-08-28_16.14.38-client.txt?dl=0

**Comment by kihira** [comment]
Seems that you may have an outdated version of FoxLib. Delete the one in
your mods folder then start the game and accept the prompt to autodownload
it

**Comment by SYMA24G** [comment]
Sorry, I did not notice that it was out of beta.
