### ISSUE TITLE
Foxtato Crash

### ISSUE THREAD

**Issue by Nerdpie** [kihira/Tails#54]
OpenEye report:

http://openeye.openmods.info/crashes/7e138da58519a76303b1819c6d388f10

The Foxtato is causing an NPE crash.
I'm not sure what is getting unloaded; I'm in the overworld when it happens.  The crash occurs within a minute of loading the world.  I am not very familiar with the dimension handling code, but my best guess would be that it is only creating one instance of the FoxtatoFakeEntity for the entire SSP server, and then trying to call 'onWorldUnload' for each dimension; completely guessing, honestly.

**Comment by kihira** [comment]
Fixed in 1.4.1
