### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by Nerdpie** [kihira/Tails#55]
I am now getting a StackOverflowException during post-init if Botania is installed.  I've grabbed a copy of the source, and the issue is caused by the implicit toString call at [Tails.java line 85] (https://github.com/kihira/Tails/blob/develop/src/main/java/kihira/tails/common/Tails.java#L85); unfortunately, this appears to be a bug in FML.

**Comment by kihira** [comment]
Ah yes, my error there. I ran into it a few times when debugging 1.4.0 and
forget to check that part in 1.4.1, I'll push an update soon

**Comment by Nerdpie** [comment]
Is this something that should be reported on the FML issue tracker?  I mean, a toString call really shouldn't result in a StackOverflow.  Unless it's a known issue and I'm overlooking something that says "don't call this function!"... That, and I don't see any existing issues related to this on the FML tracker.

Regardless, thanks for the prompt response!

**Comment by kihira** [comment]
Probably should do, I'll see if I can poke someone about it. But its better
to fix it on my end for compatibility with current forge versions
