### ISSUE TITLE
Rendering glitch in 1.8 version

### ISSUE THREAD

**Issue by CallMeFoxie** [kihira/Tails#57]
http://pastebin.com/uiGaR2YS

Works in single player but if i go on a server it glitches all all animations up and cant see my cape anymore after that until i restart

**Comment by CallMeFoxie** [comment]
Latest stable 1.8 Forge and no other mods:
http://pastebin.com/845X9dxH

**Comment by CallMeFoxie** [comment]
Video of GUI: https://drive.google.com/file/d/0B0VVagQIMPjNbkdlaUhsSm8tZU0/view

**Comment by BeatPlay** [comment]
I found a fix for it:

1. Go to singleplayer map and set up skin
2. Save skin and upload
3. Restart MC
4. Go on a Server

And it works again even with my Shaders and stuff! :D

**Comment by kihira** [comment]
Should be fixed in newer versions
