### ISSUE TITLE
tails not showing up at all on 1.8

### ISSUE THREAD

**Issue by Shadowmaster94** [kihira/Tails#59]
the tails do not render at all on forge built for 1.8 not 1.8.# but 1.8 and i tried about anything and could not fix it.

**Comment by kihira** [comment]
Make sure you are logging in and the server (if you are connected to one is in online mode).
If that doesn't work, delete the config file for tails and let is regenerate and create a new tail.

Otherwise make sure you don't have any mods that interfere with player rendering.

**Comment by kihira** [comment]
This should be fixed in the latest versions
