### ISSUE TITLE
1.8.9 Version?

### ISSUE THREAD

**Issue by LuminaDragon** [kihira/Tails#60]
You have the best tails :) 

We are wondering if there's going to be a version for 1.8.9?

**Comment by TheChronomancer** [comment]
there is now http://minecraft.curseforge.com/projects/tails/files/2297585/download

**Comment by kihira** [comment]
Woops forgot to reply to this!

Yup there is now but there is some rendering issues when crouching. Will
release a fix over the weekend hopefully
