### ISSUE TITLE
GUI menu

### ISSUE THREAD

**Issue by js199456** [kihira/Tails#63]
On each menu (Tails, Ears, Wings) the first choice on all of them appears a difuminated and its a bit hard to distinguish it.
(atleast on my client)

**Comment by kihira** [comment]
Seems fine on mine, could you provide a screenshot?

Are you using any other mods?

(Also for the future, please include a version number!)

**Comment by js199456** [comment]
i found out the problem, apparently Overwolf fps counter was displaying over it blacking it out a little bit.
