### ISSUE TITLE
[Crash] Exporting and Uploading Skin to Mojang

### ISSUE THREAD

**Issue by Master0r0** [kihira/Tails#66]
Version: Tails-1.10.2-1.8.0.jar
Attempting Export and Upload the skin to mojang causes an immediate crash to desktop.

Crash Log: http://pastebin.com/NTkjE958

**Comment by kihira** [comment]
This feature is being deprecated, the export button was supposed to be
disabled.

Basically its crashing cause I didn't add the logic to encode it to the
skin. I might add it back for now but it will be going away in the rewrite
in the future

On 11 Jul 2016 22:50, "Master0r0" <notifications@github.com> wrote:
>
> Attempting Export and Upload the skin to mojang causes an immediate crash
to desktop.
