### ISSUE TITLE
tails not invisible

### ISSUE THREAD

**Issue by hellpa** [kihira/Tails#67]
Hello. I have no idea if it is possible or not but would 
it be possible to make tails become invisble too?
![2016-08-07_16 52 30](https://cloud.githubusercontent.com/assets/20533589/17463111/afab8e3a-5cbf-11e6-8f83-092985a96824.png)
![2016-08-07_16 52 34](https://cloud.githubusercontent.com/assets/20533589/17463112/b165f94a-5cbf-11e6-98c9-619bb2b341a6.png)
![2016-08-07_16 52 44](https://cloud.githubusercontent.com/assets/20533589/17463114/b27434c8-5cbf-11e6-894d-417af257b482.png)
It is of course not really important.
Anyway I thank you for your mod and work.

**Comment by kihira** [comment]
I'm aware of this issue, should release a fix soon

**Comment by hellpa** [comment]
OK. Thank you.
