### ISSUE TITLE
Player does not log off when disconnecting 

### ISSUE THREAD

**Issue by ian70203** [kihira/Tails#70]
When you log off a server, the server thinks you're still online.
I tested this when I discovered this bug, I joined Hypixel then after "disconnecting", I went onto another server, the sounds and chat are still received and the only way to disconnect from these servers is to close Minecraft.

**Comment by kihira** [comment]
Now this is the first time I've heard of this issue.
Can you try removing Tails from your client to confirm this is caused by it?

Also what Tails and Forge version?

**Comment by ian70203** [comment]
Yes, I even tested all of my mods and the Tails mod is the one causing the problem.

Forge Version: 1.10.2-12.18.1.2089
Tails Version: 1.8.2 (latest at this time)

**Comment by ian70203** [comment]
Let me make a quick video of it happening.

**Comment by kihira** [comment]
Hmm very weird then. Can you provide me with a log after this has happened?
Are you switching from modded to vanilla server or vanilla or vanilla server?
What other mods do you have installed?

**Comment by ian70203** [comment]
Yes, I'm switching from vanilla to vanilla.
The other stuff is [here](https://github.com/ian70203/otherthings/tree/master).
What do you mean by providing a log after this has happened?
Do you mean what happens if I use the Tails mod alone or with all of my other mods?

**Comment by kihira** [comment]
The console output/log. You should see a "fml-client-latest" inside the logs folder for Minecraft. When this issue occurs, copy the log to somewhere like pastebin then send me the link. 

And hmm, I'll be honest, I'm not entirely sure what is causing this. I only list for events on connect/disconnect and don't actually cancel anything. So logs should help me in case some sort of error is occurring.

**Comment by ian70203** [comment]
Okay, the log will be posted into the otherthings repository on my profile shortly.

**Comment by ian70203** [comment]
I'm going to try to re-download the mod.

**Comment by kihira** [comment]
Ah ha interesting. It seems my mod errors on disconnect causing the disconnect to not happen even though it looks like it happens. A fix will be out soon
