### ISSUE TITLE
Tails Specific Jacket Layer Configuration

### ISSUE THREAD

**Issue by WolfieWaffle** [kihira/Tails#73]
In Minecraft there is the second layer to the skin, and you can turn parts on or off. This second layer is often used for tails or snouts when this mod is not installed. I can turn off the second layers if I have this mod, but if you are on a server and some people have the mod installed and some don't, I can't render the second layer depending on if the player seeing me has the mod or not. This leads to either no tails or duplicate tails.

So my suggestion is to allow certain layers to not render for the tails mod, like a second configuration specifically for the tails mod. You could possibly store this information as unused pixels in the skin or something. I think there are 6 items total and each are booleans, off or on, so that's like 6 pixels black or white for on or off? im not sure but I think it would be a useful feature for servers.

**Comment by kihira** [comment]
Apologies for the late follow up on this.

Are you suggesting having tails, ears etc as items instead?
Or are you looking for help with developing your own mod?
I'm not sure I fully understand.

Right now I do have each part on my own custom layer instead, this allows me fully control over who I render what on.

**Comment by WolfieWaffle** [comment]
Mostly I'm talking about if you have a skin that already has ears or a tail on skin, but the more I think about it I'm not sure it would work. My idea was to have as part of the per player tail configuration you could disable say the second head layer that displays on skins.

**Comment by kihira** [comment]
You can already disable the second head layer in the settings on Minecraft client.

As for detecting if there is a tail already, pretty much impossible to guess from the skin. Machines aren't amazing at detecting stuff like that (and I really don't feel like training a ML program to try and do it).

I used to have a system that encoded tail data onto your skin so it would work in vanilla clients but this was deprecated as it was a nightmare to maintain. This will be replaced by a new system in Tails 2.0

**Comment by WolfieWaffle** [comment]
Ahh, I see yeah I was wondering about that client system and I don't remember it working and was wondering about disabling the head layer only for other players who had the mod installed so that players with the mod did not see a second layer of ears but everyone else just saw the regular skin, but yeah that idea has many problems. Interesting that there will be a new system though, I'll look forward to that.
