### ISSUE TITLE
Not rendering shadows in 1.10

### ISSUE THREAD

**Issue by Kazekai** [kihira/Tails#75]
Models aren't rendering their shading in 1.10, no idea why not. Far as I know we don't have anything installed that changes the way minecraft renders.

Mod list for the private server we're playing on.

autopackager-1.6.3.jar
Bagginses-1.10.2-3.0.4g.jar
Baubles-1.10.2-1.3.8.jar
BBG-1.9.4-5.0.0.jar
BetterBuildersWands-1.10.2-0.9.3.187+c619800.jar
Botania r1.9-339.jar
Chameleon-1.10-2.2.2.jar
Chisel-MC1.10.2-0.0.7.7.jar
chiselsandbits-12.9.jar
CodeChickenCore-1.10.2-2.4.0.100-universal.jar
CodeChickenLib-1.10.2-2.5.0.178-universal.jar
compatlayer-1.10-0.1.6.jar
CraftTweaker-1.10.2-3.0.16.jar
CustomMainMenu-MC1.10.2-2.0.2.jar
denseores-1.11-alpha-1.0.0.jar
DrawersBits-1.10.2-0.35.jar
EnderCore-1.10.2-0.4.1.61-beta.jar
EnderIO-1.10.2-3.0.1.149_beta.jar
EnderStorage-1.10.2-2.2.0.96-universal.jar
extrautils2-1.10.2-1.1.3a.jar
ExtremeReactors-1.10.2-0.4.5.23.jar
FastLeafDecay-v11.jar
Forgelin-1.2.0.jar
FTBLib-1.10.2-3.2.3.jar
FTBUtilities-1.10.2-3.2.4.jar
GraveStone Mod 1.5.10.jar
inventorypets-1.10-1.4.9.jar
InventoryTweaks-1.62-dev-66.jar
ironchest-1.10.2-7.0.11.797.jar
jei_1.10.2-3.13.6.393.jar
journeymap-1.10.2-5.3.3.jar
JustEnoughResources-1.10.2-0.5.8.98.jar
LootBags-1.10.2-2.3.0.jar
Mantle-1.10.2-1.1.3.jar
MCMultiPart-1.3.0-universal.jar
ModTweaker2-2.0.8.jar
Morpheus-1.10.2-3.1.13.jar
MouseTweaks-2.6.4-mc1.10.2.jar
MTLib-1.0.0.jar
natura-1.10.2-4.1.0.17.jar
PixelExtras-1.10.2-2.2.4-universal.jar
Pixelmon-1.10.2-5.0.0-universal.jar
QuantumStorage-1.10.2-3.2.16.jar
RebornCore-1.10.2-2.8.5.79-universal.jar
refinedstorage-1.2.14.jar
ResourceLoader-MC1.9.4-1.5.1.jar
roots-0.208.jar
ShadowMC-1.10.2-3.6.0.jar
SleepingBag-1.10.2-1.4.0.jar
StorageDrawers-1.10.2-3.5.16.jar
VeinMiner-1.9-0.35.3.595+a46c1b0.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10.2-1.1.9.jar
Wawla-1.10.2-2.3.1.214.jar
zerocore-1.10.2-0.0.8.2.jar

**Comment by kihira** [comment]
Sorry for the late follow up on this.

Did removing Tails fix the rendering issue with shadows then I'm assuming?
Do you a lot of OpenGL errors in your clients console log?
