### ISSUE TITLE
Game crashs on 1.8.9

### ISSUE THREAD

**Issue by Akame-Zero** [kihira/Tails#76]
Crash report:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: kihira/tails/client/gui/GuiEditor

**Comment by kihira** [comment]
Can you try deleting FoxLib and manually downloading it from CurseForge?

The auto downloader was broken at the time
