### ISSUE TITLE
Tails, wings etc not showing up

### ISSUE THREAD

**Issue by KamiSami** [kihira/Tails#77]
See the image http://pasteboard.co/3rlfnZnF7.png

I do not know if you are still ever planning to update the mod again but would be awesome if you did.

Also forgot to mention, using latest file for 1.10.2 Minecraft.

**Comment by ian70203** [comment]
Weird, maybe some other mod is conflicting with it?

**Comment by kihira** [comment]
Are you using Mo'bends, additional player models etc?
This does change how players are rendering and isn't compatible with the current layering system

**Comment by Nepeta-S-Leijon** [comment]
A friend of mine had this exact same problem.  Changing her skin resolved the problem, I suspect that the skin may have colors in the unused areas, which is causing Tails to render no tail at all, instead of what you choose (IDK if this makes much sense, I'm bad at english sorry :<)

**Comment by kihira** [comment]
Hmm that is quite possible.

The skin system is being deprecated in future versions so that should hopefully no longer be an issue.
But to solve the issue, if you make the top left hand corner of your skin (where Tails stores data on it) to transparent, it should prevent it.
