### ISSUE TITLE
Dragon/Lizard, Cat, and both devil tails not properly syncing with sneaking

### ISSUE THREAD

**Issue by Dragend** [kihira/Tails#80]
https://gyazo.com/035804940803b503864625b399f84303
https://gyazo.com/8c096b378aa1556af1c011b403567145
https://gyazo.com/9f536b447a695b7f08f05dff1a765450

this exists in 1.11.2 and also 1.10.2

**Comment by kihira** [comment]
Thanks, I believe this is caused as I switched over to the layers system and forgot to take sneaking into account, should have a fix out in next release
