### ISSUE TITLE
issues on 1.11.2 tails and lib conflict on start up

### ISSUE THREAD

**Issue by warcommando2** [kihira/Tails#81]
hi there;

this is the start up log on the issue i am having. I am redoing my modpack called HermletteCraft Chronicles on curse/twitch. 

https://pastebin.com/sStnmngV

This is the list of mods i am using to try and update my pack the way i intended it to be. This shows tails and 9tailslib as if it was on. Ifv i remove them it runs fine. If someone can help me narrow it down as to why its causing this error that would be great!

Aroma1997Core (by Aroma1997)
The Rpg Inventory and ClassArmor Mod (by senpaisubaraki)
Simply Conveyors & More (by Zundrel)
Botania: Garden of Glass (by Vazkii)
Signpost (by Gollorum)
Animania (by Purplicious_Cow)
Random Things (by lumien231)
Inventory Tweaks (by Kobata)
ShetiPhianCore (by ShetiPhian)
Aquaculture (by Shadowclaimer)
Dynamic Lights (by AtomicStryker)
Chameleon (by jaquadro)
Crafting Tweaks (by BlayTheNinth)
Botania (by Vazkii)
Guide-API (by TehNut)
DecoCraft2 (by RazzleberryFox)
EverlastingAbilities (by kroeser)
IvToolkit (by Ivorforce)
Bookshelf (by darkh4x)
Iron Chests (by progwml6)
Bookshelf API Library (by TeamBRModding)
Wolf Armor and Storage (by CenturionFox)
LLibrary (by iLexiconn)
Lore Expansion (by theCyanideX)
MultiStorage (by ShetiPhian)
Packing Tape (by gigaherz)
Multi Page Chest (by CubeX2)
Resource Loader (by lumien231)
BotaniaVisualizer (by mariri2u)
Terraqueous (by ShetiPhian)
BetterFps (by Guichaguri)
Class Armor : Necromancer and Paladin (by senpaisubaraki)
Level Up! (by BeetoGuy)
HelpFixer (by matthewprenger)
McJtyLib (by McJty)
Chisels & Bytes (by Belgabor)
Extra Utilities (by RWTema)
NetherPortalFix (by BlayTheNinth)
AtomicStryker's Infernal Mobs (by AtomicStryker)
Dynamic Surroundings (by OreCruncher)
ForgeEndertech (by EnderLanky)
Pam's HarvestCraft (by MatrexsVigil)
Cyclops Core (by kroeser)
Gender Mod (by iPixeli)
BdLib (by bdew)
Realistic Torches (by ChaosTheDude)
Crystal Caves (by steelfeathers)
Biomes O' Plenty (by Glitchfiend)
Industrial Craft (by Player)
Vertical Slabs (by steelfeathers)
Shadowfacts' Forgelin (by shadowfactsmc)
JurassiCraft2 (by Codyrex78000)
BetterBedrockGen (by Gigabit1011)
Overlord (by The_Fireplace)
Chance Cubes (by turkey2349)
Chisel (by tterrag1098)
Class Armor : Beast Master (by senpaisubaraki)
MalisisBlocks (by Ordinastie)
Better Foliage (by octarine_noise)
Cooking for Blockheads (by BlayTheNinth)
Shoulder Surfing Reloaded (by suinhas)
NotEnoughIDs (by fewizz)
CXLibrary (by CubeX2)
Dark Roleplay Medieval (by JTK222)
Quality Tools (by Tmtravlr)
Chisels & Bits (by AlgorithmX2)
Sound Filters (by Tmtravlr)
Grim Pack (by grim3212)
Stellar API (by abab9579)
SwingThroughGrass (by exidex)
Platforms (by ShetiPhian)
AromaBackup (by Aroma1997)
Literal Ascension (by JamiesWhiteShirt)
Spartan Shields (by ObliviousSpartan)
Waystones (by BlayTheNinth)
Scaling Health (by SilentChaos512)
Earthworks (by Alsnder)
Stellar Sky (by abab9579)
Homecraft Mineware (by Rorax)
Class Armor : Berserker, Mage and Archer (by senpaisubaraki)
VeinMiner (by Portablejim)
Recurrent Complex (by Ivorforce)
MalisisDoors (by Ordinastie)
Blood Magic (by WayofTime)
Alternate Terrain Generation (by TTFTCUTS)
Redstone Paste (by FyberOptic)
Vending block (by kamildanak)
Mantle (by mDiyo)
MrCrayfish's Furniture Mod (by Mr_Crayfish)
Baubles (by azanor)
Roots (by elucent)
Bloodmoon (by lumien231)
Concrete Mod (by Dbrown55)
Tinkers Construct (by mDiyo)
Better Combat Mod (by Ironfistss)
MalisisSwitches (by Ordinastie)
Gendustry (by bdew)
Storage Drawers (by jaquadro)
Forestry (by SirSengir)
AmbientSounds 2.0 (by CreativeMD)
Advanced Chimneys (by EnderLanky)
Wearable Backpacks (by koppeh)
Placeable Items (by Ferdz)
Tim's Expansion Mod (by buradin83)
Potion Core (by Tmtravlr)
Rustic (by thatguy3039)
MalisisCore (by Ordinastie)
Rope Bridge (by LordCazsius)
Levels (by TheXFactor117)
Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)
Building Kit (by Stickxy)
Dark Roleplay Core (by JTK222)
Common Capabilities (by kroeser)
Drawers & Bits (by Belgabor)
EvilCraft (by kroeser)
Embers (by elucent)
Silent Lib (by SilentChaos512)
Corail Pillar (by Corail31)
ElecCore | Rendering Library (by Elec332)
SubLib (by senpaisubaraki)
Custom NPCs (by Noppes)
CompatLayer (by McJty)
EnhancedVisuals (by CreativeMD)
Neat (by Vazkii)
The One Probe (by McJty)
More Player Models (by Noppes)
Architect (by SangarWasTaken)
Mouse Tweaks (by YaLTeR97)
Doggy Talents (by 902cf6edf2a9433da4d835ce0f026473)
Just Fashion (by senpaisubaraki)
Tough As Nails (by Glitchfiend)
Stats Keeper (by Terrails)
Realm Of Yendor's Artifacts of the Lost (by machinespray)
Morpheus (by Quetzi)
BiblioCraft (by JDSinclair)
Vampirism - Become a vampire! (by maxanier)
Tinkers' Addons (by oitsjustjose)
Mowzie's Mobs (by BobMowzie)
TAN Campfire Spit (by WolfieWaffle)
Simple Fluid Tanks (by Zarathul)
FTBLib (by FTB)
FTB Utilities (by FTB)
ThutCore (by patnevis)
Thut's Elevators (by patnevis)
Master Builders Mod (by pupmod)
Xaero's Minimap (by xaero96)
CraftTweaker (by jaredlll08)
FTB Tweaks (by FTB)
LibrarianLib (by yrsegal)
Reforged (by ThexXTURBOXx)
Natura (by mDiyo)
CodeChicken Lib 1.8.+ (by covers1624)
Ender Storage 1.8.+ (by covers1624)
ZeroCore (by ZeroNoRyouki)
Extreme Reactors (by ZeroNoRyouki)
MCMultiPart (by amadornes)
Just Enough Resources (JER) (by Way2muchnoise)
Not Enough Items 1.8.+ (by covers1624)
Fast Leaf Decay (by Olafskii)
Aroma1997s Dimensional World (by Aroma1997)
MmmMmmMmmMmm (by bonusboni)
Angel Ring To Bauble (by Portablejim)
DeathQuotes / Death Quotes (by andrenoel1)
Farseek (by delvr)
Streams (by delvr)
Mo' Bends (by iwoplaza)
DynmapForge (by mikeprimm)
Mekanism Generators (by aidancbrady)
Mekanism Tools (by aidancbrady)
Just Enough Items (JEI) (by mezz)
Mekanism (by aidancbrady)
CustomizedLore (by TheSatanicSanta)

-CryoTech/warcommando2

**Comment by kihira** [comment]
I'm not sure what the issue is here, you didn't state one.

Can you clarify the issue you are having?

**Comment by warcommando2** [comment]
as soon as it launch's it crash's with your mods enabled, this is the only log i have with it is the start up log. When i launch it through the curse or any other launcher i get that report. When i do have the library file off it loads the tails mod fine but no proper GUI screen because the library file is not present. 

hit play on custom profile
opened the options in the minecraft launcher used below augment saved and hit play
startup/crashlog on pastebin

edit: Found the log - latest
https://pastebin.com/WC4FCGLN

java augment:
-Xmx7156m -Xms512m -XX:PermSize=512m

**Comment by kihira** [comment]
This is not an issue with my mod (Tails), this is an issue with NineTailLib (https://mods.curse.com/mc-mods/minecraft/264381-ninetaillib).

I recommend you send that pastebin link to them. It seems they have a repo here: https://github.com/TeamMD5/NineTailLib/issues

**Comment by warcommando2** [comment]
ok thank you i guess some how i got it mixed up LOL i copied it all over
