### ISSUE TITLE
Static Ears Bug in 1.11.2's Version

### ISSUE THREAD

**Issue by WilliamBlaze** [kihira/Tails#82]
as the name implies, the ears are not moving with the rotation of the player's head. they remain at a fixed point floating above the player's position. down below i'll give a screen shot comparison of the same ears from the current version and an earlier version of this mod, as the visual aid might better convey the issue. 

https://prnt.sc/fgdzda - 1.11.2
https://prnt.sc/fgdz7v - 1.11.2

https://prnt.sc/fgds1u - 1.7.10
https://prnt.sc/fgdrph - 1.7.10

**Comment by kihira** [comment]
Thanks for the report, I believe I know the cause and should have a fix out in the next version :)

**Comment by WilliamBlaze** [comment]
http://prntscr.com/fkt4ps
it appears as if the problem is still persisting in the tails-1.11.2-1.9.1 update sorry for writing here again but considering its the exact same issue it felt more appropriate to post it here then to open a separate report

**Comment by kihira** [comment]
Hmm odd, I've tested and it was working fine for me.
Are you using any other mods that might change the player model such as MorePlayerModels, Mo' Bends etc?

**Comment by WilliamBlaze** [comment]
MorePlayerModels to be exact, though i didnt think that would cause any issues considering i only use it to load my HD minecraft skin on my character since default minecraft doesnt allow skins with red higher then 64x64 - that and i didnt see a notice for incompatibility issues between the two prior to this event

there anything i can do to correct it or do i need to uninstall moreplayermodels' all together for tails to work?

**Comment by kihira** [comment]
They used to work together, then I switched to using a layer based system in MC1.8 which broke that compat.
I readded a way to use the "legacy" system in MC1.9 but seems that the legacy renderer didn't trigger and it might be using the layer based system.
I'll add a config to enable forcing the legacy renderer which should fix it and try to find out why its not automatically enabling.

**Comment by VerMako6** [comment]
That's what I did. I took more player models out of the mods folder and it works fine for me.

**Comment by kihira** [comment]
Reproduced the issue with MPM, unfortunately not going to be an easy fix.

He replaces the player model in postinit after my mod (or he's not replacing it the correct way to support vanilla skins with different width arms) which is causing it to not properly render.

I'll keep working on a fix but might take a few days

**Comment by kihira** [comment]
1.9.2 is now released which contains a fix
