### ISSUE TITLE
Tails not working with MorePlayerModels

### ISSUE THREAD

**Issue by VerMako6** [kihira/Tails#84]
When i Crouch, The tail looks very weird! Can you please Make tails compatible with MorePlayerModels?

Thanks, 
-Mako

**Comment by kihira** [comment]
Need more details.

- What version of Forge?
- What version of Tails?
- What version of MPM?
- Is this affecting all tails or just one? If one, which one?

**Comment by VerMako6** [comment]
1.11.2 forge 13.20.0.2315
Tails 1.9.1
MorePlayerModels_1.11.2(26jan17)

**Comment by Flexico** [comment]
I have this problem as well; My ears also don't move with my head.

1.11.2 Forge 13.20.0.2312
Tails 1.9.1
MorePlayerModels 1.11.2(26jan17)

**Comment by kihira** [comment]
Reproduced issue, working on fix

**Comment by kihira** [comment]
Fixed in a2996c4

**Comment by kihira** [comment]
1.9.2 is now released which contains this fix
