### ISSUE TITLE
Crash on server start with Tails.

### ISSUE THREAD

**Issue by Wizardon777** [kihira/Tails#85]
Crash log included.
[crash-2017-06-15_23.38.05-server.txt](https://github.com/kihira/Tails/files/1081888/crash-2017-06-15_23.38.05-server.txt)

**Comment by kihira** [comment]
Thanks for the report, not sure why it's occurring as I didn't change anything in that area. Will look into it over this weekend

**Comment by Iiridayn** [comment]
Same crash, fewer core mods installed. Thank you for this mod :).

**Comment by kihira** [comment]
Fixed in 1.9.2, sorry for the delay!
