### ISSUE TITLE
Tails still render when invisibility is enabled in 1.10 and 1.11

### ISSUE THREAD

**Issue by Foxite** [kihira/Tails#87]
This might be in 1.8 and 1.9, but I have't tested it and I need sleep. I do know that it works properly in 1.7.10.
![screenshot from 2017-06-28 23-34-36](https://user-images.githubusercontent.com/20421657/27661376-5fa44b66-5c5a-11e7-9ae5-583f7c7a859e.png)

**Comment by kihira** [comment]
Totally did not forget about this bug >.>

Thanks for making an issue, will release a fix just before the 1.12 port

**Comment by kihira** [comment]
Fixed in 1.9.3 for 1.11.2 https://minecraft.curseforge.com/projects/tails/files/2445515

Should have a final release for 1.10.2 "soon" as well and will include this fix
