### ISSUE TITLE
Muzzle and Ears shifting when turning horizontally at a quick speed and then opening inventory

### ISSUE THREAD

**Issue by Dragend** [kihira/Tails#91]
https://gyazo.com/8f3c60700de285ed6949d46a4ce2d27f
https://gyazo.com/7f6d1491b42f81668863a7061f6c6b1d
https://gyazo.com/7f6d1491b42f81668863a7061f6c6b1d

I also tested it where the tails mod is the only mod, and it still does this

I'm running version 1.11.2

**Comment by kihira** [comment]
Same #92, never noticed this one earlier.
Will close this for now and will update other issue
