### ISSUE TITLE
Small but, slightly annoying issue.

### ISSUE THREAD

**Issue by shanej0nes** [kihira/Tails#95]
Its been happening a lot lately with my ears only, my ears are shifted to the left of my player skin when I look in my inventory GUI. I don't know what could be causing it so, I hope you can.
![2017-09-20_01 46 35](https://user-images.githubusercontent.com/32126018/30635269-c1e8948e-9da6-11e7-82f3-c0852925f804.png)

**Comment by kihira** [comment]
Need a bit more information:
What version of Tails are you running?
Does it only happen in the GUI?

**Comment by shanej0nes** [comment]
I'm running Tails 1.12-1.10.0 with Forge 1.12.1-14.22.0.2474. As far as I've noticed, it only happens in the inventory GUI.

**Comment by kihira** [comment]
Seems to be a duplicate of #92 so will close this one
